SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `testdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `cppforo_forums`
--

CREATE TABLE IF NOT EXISTS `cppforo_forums` (
`fid` int(11) NOT NULL,
  `forum_name` varchar(100) NOT NULL,
  `lastposter` int(11) NOT NULL,
  `lastpost` int(11) NOT NULL,
  `lastposter_name` varchar(100) NOT NULL,
  `is_staff` tinyint(1) NOT NULL DEFAULT '0',
  `is_admin` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `cppforo_forums`
--

INSERT INTO `cppforo_forums` (`fid`, `forum_name`, `lastposter`, `lastpost`, `lastposter_name`, `is_staff`, `is_admin`) VALUES
(1, 'Example Forum', 0, 1, 'Example Post', 0, 0);

-- --------------------------------------------------------

--
-- Table structure for table `cppforo_posts`
--

CREATE TABLE IF NOT EXISTS `cppforo_posts` (
`pid` int(11) NOT NULL,
  `content` text NOT NULL,
  `author` int(11) NOT NULL DEFAULT '0',
  `tid` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `cppforo_posts`
--

INSERT INTO `cppforo_posts` (`pid`, `content`, `author`, `tid`) VALUES
(1, 'This post was automatically generated by the system.', 0, 1),
(2, 'bleh', 0, 2),
(3, 'bleh', 0, 3),
(4, 'bleh', 0, 4);

-- --------------------------------------------------------

--
-- Table structure for table `cppforo_settings`
--

CREATE TABLE IF NOT EXISTS `cppforo_settings` (
  `name` varchar(100) NOT NULL,
  `content` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `cppforo_settings`
--

INSERT INTO `cppforo_settings` (`name`, `content`) VALUES
('members_only', '0'),
('site_name', 'Example Site'),
('site_url', 'localhost:2555');

-- --------------------------------------------------------

--
-- Table structure for table `cppforo_topics`
--

CREATE TABLE IF NOT EXISTS `cppforo_topics` (
`tid` int(11) NOT NULL,
  `topic_name` varchar(80) NOT NULL,
  `author` int(11) NOT NULL DEFAULT '0',
  `is_locked` tinyint(1) NOT NULL DEFAULT '0',
  `fid` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `cppforo_topics`
--

INSERT INTO `cppforo_topics` (`tid`, `topic_name`, `author`, `is_locked`, `fid`) VALUES
(1, 'Example Topic', 0, 0, 1),
(2, 'test', 0, 0, 1),
(3, 'test', 0, 0, 1),
(4, 'test', 0, 0, 1);

-- --------------------------------------------------------

--
-- Table structure for table `cppforo_users`
--

CREATE TABLE IF NOT EXISTS `cppforo_users` (
`uid` int(11) NOT NULL,
  `gid` int(11) NOT NULL DEFAULT '1',
  `username` varchar(100) NOT NULL,
  `password` varchar(102) NOT NULL,
  `salt` varchar(80) NOT NULL,
  `session` varchar(100) NOT NULL DEFAULT '0',
  `is_banned` tinyint(1) NOT NULL DEFAULT '0',
  `is_mod` tinyint(1) NOT NULL DEFAULT '0',
  `is_admin` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `cppforo_users`
--

INSERT INTO `cppforo_users` (`uid`, `gid`, `username`, `password`, `salt`, `session`, `is_banned`, `is_mod`, `is_admin`) VALUES
(1, 1, 'Admin', 'password', '', '0', 0, 1, 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cppforo_forums`
--
ALTER TABLE `cppforo_forums`
 ADD PRIMARY KEY (`fid`);

--
-- Indexes for table `cppforo_posts`
--
ALTER TABLE `cppforo_posts`
 ADD PRIMARY KEY (`pid`);

--
-- Indexes for table `cppforo_settings`
--
ALTER TABLE `cppforo_settings`
 ADD PRIMARY KEY (`name`);

--
-- Indexes for table `cppforo_topics`
--
ALTER TABLE `cppforo_topics`
 ADD PRIMARY KEY (`tid`);

--
-- Indexes for table `cppforo_users`
--
ALTER TABLE `cppforo_users`
 ADD PRIMARY KEY (`uid`), ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cppforo_forums`
--
ALTER TABLE `cppforo_forums`
MODIFY `fid` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
--
-- AUTO_INCREMENT for table `cppforo_posts`
--
ALTER TABLE `cppforo_posts`
MODIFY `pid` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `cppforo_topics`
--
ALTER TABLE `cppforo_topics`
MODIFY `tid` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `cppforo_users`
--
ALTER TABLE `cppforo_users`
MODIFY `uid` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
